# Generated by Django 5.2.4 on 2025-08-09 00:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('boards_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=25)),
                ('description', models.TextField(max_length=250)),
                ('status', models.CharField(choices=[('FR', 'to-do'), ('SO', 'in-progress'), ('JR', 'review'), ('SR', 'done')])),
                ('priority', models.CharField(choices=[('FR', 'low'), ('SO', 'medium'), ('JR', 'high')])),
                ('due_date', models.DateField(auto_now=True)),
                ('assignee_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned', to=settings.AUTH_USER_MODEL)),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boards_app.board')),
                ('reviewer_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewer', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
