# Generated by Django 5.2.4 on 2025-07-19 02:35

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register_app', '0003_rename_userprofile_cutomuser'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CutomUser',
            new_name='CustomUser',
        ),
    ]
